### ISSUE TITLE
Unique prefix matching?

### ISSUE THREAD

**Issue by c-blake** [madprops/nap#1]
Something that is to my knowledge new as-of https://github.com/c-blake/cligen is accepting any prefix like `--opti` for a long option as long as it is "unique" in its namespace.  Tools like the Mercurial version control system and long before it gnuplot and debuggers have had this kind of thing for keywords forever (and I also use it for enum's or subcommand names), but it's also quite nice for long-options.  It's like TAB-completion without having to hit TAB (or to either A) program completions for every shell under the sun or B) always have to type the full string).  Nim's stdlib `CritBitTree` makes it really easy, too.

**Comment by madprops** [comment]
I think I understand. You want for instance --peri to match --peripheral etc?

**Comment by madprops** [comment]
As long as there are no conflicts.

**Comment by c-blake** [comment]
Yeppers.  Sounds like you get it.

And just to elaborate, with `CritBitTree` (a variant of a Patricia Trie) you can just load it up like a Table/dictionary (`import critbits; var cb: CritBitTree[void]; cb.add key1; cb.add key2; ...`).  Then when the CL user presents you some string you can use `iterator keysWithPrefix*[T](c: CritBitTree[T], prefix: string; longestMatch = false): string` to "expand it"/see if it expands uniquely.  Couple more details you can see in `proc lengthen` in https://github.com/c-blake/cligen/blob/master/cligen/parseopt3.nim

**Comment by c-blake** [comment]
(And, of course, you could also get this done with regular old sort and binary search, but that's probably a bit more coding effort.)

**Comment by madprops** [comment]
Made an initial implementation of this. Just did some manual checks. https://github.com/madprops/nap/blob/master/src/nap.nim#L301

**Comment by c-blake** [comment]
I only read your impl, did not try anything out, but I think you want `startsWith` not `contains`.  Contains will let a person typing `--dofoo` match an expected `--foo`.  It's admittedly a bit of a judgement call since we're already being "flexibly accepting", but that feels a little too loose to me.

And yeah, even a linear re-scan is a viable impl as long as you check for an exact match _first_ (which I think you do) because one key could be the prefix of another (as in --foo --foobar without any abbreviation tricks) and you need the exact match to prevail.

I'm honestly surprised this has not been a more popular keystroking/CLI framework feature.  It's almost as obscure as Nim itself.  Trying to help change that in my own little way.  It both lets CL authors/script authors document things with long identifiers but also does not force heat-of-the-moment keystrokers to use the whole thing or to remember the short options.  Indeed, it basically creates a "discrete continuum of abbreviations" starting with "full long options" and ending with "as short as the CL author can muster via de-conflicting prefixes".  One might theorize that a "short-option-less" command-options system would be only a minor burden if all the long-option systems did this.  The dash-dash could even fall away, as in, e.g. `gcc`'s options syntax.

{Personally I have good recall for 1-letter options and also like/frequently use "combining syntax" like, e.g. "du -scBG", but I understand I am rare. Honestly, liking that sort of combining syntax so much was one of the things that initially motivated me to write `cligen`, but I learned a few things along that journey.}

**Comment by madprops** [comment]
Yeah it definitely needs to be startsWith, not contains. 

What I like about long options is that it's obvious what it's doing, no need to memorize. But combining short options like -snB is very powerful. Recently I added support for "alts" to be able to do this.

**Comment by c-blake** [comment]
Yeah, the continuum of abbreviation gives users a wide choice rather than forcing explicitness.  What is ideal definitely varies between "interactive sessions" vs. "scripted invocation".  Anyway, feel free to close this out once you get it all working/tested.
